import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(channel="chrome", headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://hostnplay.com/")
    page.get_by_role("link", name="Sign in").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("demo@hostnplay.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Demo12.")
    page.get_by_role("button", name="Sign in").click()
    page.get_by_role("button", name="Create Game").click()
    page.get_by_text("x", exact=True).click()
    page.get_by_text("Create New Game").click()
    page.get_by_text("Upload Your ImageClick to").click()
    page.locator("body").set_input_files("no-avatar.jpg")
    page.locator("#outlined-adornment-weight").first.click()
    page.locator("#outlined-adornment-weight").first.fill("Call of duty tounament")
    page.locator("#outlined-adornment-weight").first.click()
    page.locator("#outlined-adornment-weight").first.press("ArrowLeft")
    page.locator("#outlined-adornment-weight").first.press("ArrowLeft")
    page.locator("#outlined-adornment-weight").first.press("ArrowLeft")
    page.locator("#outlined-adornment-weight").first.press("ArrowLeft")
    page.locator("#outlined-adornment-weight").first.press("ArrowLeft")
    page.locator("#outlined-adornment-weight").first.press("ArrowLeft")
    page.locator("#outlined-adornment-weight").first.fill("Call of duty tournament")
    page.locator("#outlined-adornment-weight").first.press("ArrowRight")
    page.locator("textarea").click()
    page.locator("textarea").fill("Fun tournament")
    page.locator(".search-wrapper").first.click()
    page.get_by_text("PC").click()
    page.get_by_text("XboxOne").click()
    page.get_by_text("XboxOne").click()
    page.get_by_text("XboxOne").click()
    page.get_by_text("PS4").click()
    page.get_by_text("PS5").click()
    page.get_by_text("AI AssistantYou have 8 ai credit leftOpen AIAdd CommunityThe game will be added").click()
    page.locator(".search-wrapper.searchWrapper.singleSelect").click()
    page.get_by_text("FPS").click()
    page.get_by_text("AI AssistantYou have 8 ai credit leftOpen AIAdd CommunityThe game will be added").click()
    page.locator("#outlined-adornment-weight").nth(2).click()
    page.locator("#outlined-adornment-weight").nth(2).fill("98")
    page.get_by_role("button", name="Next").click()
    page.locator("#outlined-adornment-weight").first.click()
    page.locator("#outlined-adornment-weight").first.fill("test")
    page.locator("div:nth-child(3) > div > #multiselectContainerReact > .search-wrapper").click()
    page.get_by_role("list").get_by_text("None").click()
    page.locator("#outlined-adornment-weight").nth(1).click()
    page.locator("#outlined-adornment-weight").nth(1).fill("Bring Mic")
    page.locator("#outlined-adornment-weight").nth(2).click()
    page.locator("#outlined-adornment-weight").nth(2).fill("No Cheating")
    page.get_by_role("button", name="Submit").click()
    page.get_by_text("28").click()
    page.locator("input[type=\"time\"]").click()
    page.locator("input[type=\"time\"]").fill("20:30")
    page.get_by_role("button", name="Generate").click()
    page.get_by_role("button", name="Schedule").click()
    page.get_by_role("link").filter(has_text=re.compile(r"^$")).click()
    page.locator("div:nth-child(11) > .CardMain").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
